Refatora envio de notificação de vencimento de assinatura
apyb/associados pull request #233
Opened 2021-12-17 01:53 UTC by cuducos

### De onde chegou essa refatoração?

Quando li a #232, resolvi dar uma olhada. Achei o código confuso de entender para uma pessoa nova no repositório, e fui refatorando, extraindo etapas da abstração em funções e processos mais atômicos, tanto no comando quanto no teste.

A ideia era apenas interagir com o código para aprender o que ele faz e, se possível, arrumar algum bug como o comentado na _issue_, ou como os comentados no arquivo de testes…

Mas… demorei a entender a lógica e arrumar esses erros e esse PR parece mais uma reescrita do zero — como revisar isso é bem difícil, **tudo bem se ninguém topar e só fechar sem _mergear_** hehehe… mas, caso interesse, **segue a descrição técnica** do PR!

### O problema: manipulação da `datetime`, `date` e fuso-horário

Acredito que parte do problema (por exemplo, o teste que falhava só às vezes) se deve a confusão de fuso-horário na conversão de `datetime` para `date`:

```python
>>> timezone.now().date()
datetime.date(2021, 12, 17)

>>> pytz.timezone(settings.TIME_ZONE).normalize(timezone.now()).date()
datetime.date(2021, 12, 16)
```

Repare que sem normalizar o `datetime` antes, o dia fica 17 — mas hoje é dia 16 no fuso horário do projeto (`settings.TIME_ZONE`)… só que em UTC já é dia 17, então, se não normalizar, dá confusão.

Até descorbir isso, eu já tinha revirado o código todo e reescrito praticamente 90% desse PR, então resolvi sugerir essas melhorias, pois:

* Isolo algumas funções que podem ser reparoveitadas, como `send_apyb_mail` e o _context manager_ `translate`
* O novo código é mais alto nível (sem tanta manipulação de datas, aproveitando APIs alto níveis que não existiam há um tempo, com queries com `__date` para o ORM lidar com a busca de `date` em um campo `datetime`, testes mais atômicos, etc.)
* Redução significativa do número de consultas ao banco de dados (mudando a lógica de busca dos pagamentos, utilizando o `prefetch_related`, etc.)
* Código mais enxuto, eliminando algumas repetições

Para tentar ajudar quem for revisar, vou adicionar comentários em alguns blocos ; )

2021-12-17 01:55 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +        translation.deactivate()
A ideia é que no futuro esse _context manager_ possa ser extraído para um módulo que faça mais sentido, e reutilizado em outras partes do projeto.

2021-12-17 01:55 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +    return send_mail(**kwargs)
A ideia é que no futuro essa função possa ser extraído para um módulo que faça mais sentido, e reutilizade no lugar da `send_mail` nativa.

2021-12-17 01:56 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +ALERT_DAYS = (60, 30, 15, 7, 1)
Essas são as os dias _antes_ de vencer nos quais mandamos email (60 dias antes de vencer, 30 dias antes de vencer e assim por diante até a véspera do vencimento).

2021-12-17 01:57 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +            yield TIME_ZONE.normalize(when).date()
Aqui convertemos aqueles números inteiros em datas normalizadas para o fuso horário do projeto.

2021-12-17 02:02 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +        )
Essa _subquery_ seleciona membros que tem o vencimento _além_ de 60 dias, ou seja, gente para quem a gente não vai mandar email — mesmo se esse membro tiver um outro pagamento que vence em uma das nossas datas alvo.

Por exemplo:

A pessoa tem um pagamento que é válido até daqui a 7 dias, mas ela já renovou ontem. Ela vai ter dois pagamentos:
* o antigo apareceria na nossa busca, pois pegamos pagamentos que vencem em 7 dias
* o novo, com essa _sub-query_, faz o ID desse membro ir para uma lista de exclusão na _query_ principal, fazendo com que o antigo não apareça mais na nossa busca

2022-01-03 23:06 UTC, mazulo commented
@cuducos só agora que vi seu PR! Acho a ideia muito boa e vou tirar um tempo pra revisar ele. Também to vendo que ta simplificando bastante as coisas

2022-01-15 22:18 UTC, mazulo approved these changes

2022-02-02 12:32 UTC, rennerocha commented on app/payment/management/commands/renewal_alert.py
> +ALERT_DAYS = (60, 30, 15, 7, 1)
**sugestão** Renomear essa variável para `DAYS_BEFORE_EXPIRATION_TO_ALERT`, assim fica mais claro o que esses números mágicos significam.

2022-02-02 12:34 UTC, rennerocha commented on app/payment/management/commands/renewal_alert.py
> +            yield TIME_ZONE.normalize(when).date()
**pergunta (quase um nitpick)** Precisamos mesmo nos incomodar com o fuso horário da notificação? Mandar a notificação 3-4h antes/depois do horário não é algo que influenciaria muito no objetivo.

2022-02-02 14:22 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +            yield TIME_ZONE.normalize(when).date()
> Precisamos mesmo nos incomodar com o fuso horário da notificação?

Em termos de UX, diria que não. Mas em termos de arquitetura de software, fica muito mais simples escrever os testes fazendo essa normalização: assim não (a) caímos em testes que falham dependendo da hora do dia ou do fuso horário de quem roda os testes, nem (b) temos que complexificar o teste para tolerar um dia ante sou depois sem ter garantias de que esse era o caso, ou ainda sem (c) reimplementar a lógica de decidir se o dia esperado no teste é hoje, amanhã ou ontem…

2022-02-02 21:22 UTC, rougeth requested changes

2022-02-02 21:22 UTC, rougeth commented on app/payment/management/commands/renewal_alert.py
> +        translation.deactivate()
@cuducos os templates dos emails já estão em português, certo? Faz sentido a gente ativar tradução aqui? Confesso que fiquei surpreso que algumas strings foram escritas em inglês e depois traduzidas. Não sei qual foi o motivo na época que foi feito, mas hoje não me parece fazer muito sentido. O que acha?

2022-02-02 21:22 UTC, rougeth commented on app/payment/management/commands/renewal_alert.py
> +DAYS_BEFORE_EXPIRATION_TO_ALERT = (60, 30, 15, 7, 1)
Boa! Ficou bem mais claro!

2022-02-02 21:22 UTC, rougeth commented on app/payment/management/commands/renewal_alert.py
> +        )
O que acha de deixar um comentário no código com o exemplo? Foi mais fácil de entender o método lendo o seu comentário hahaha

2022-02-03 00:37 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +        translation.deactivate()
Eu **acho** que o _locale_, nesse caso influencia na formatação da data (que é usada nos emails), não?

2022-02-03 00:47 UTC, cuducos commented on app/payment/management/commands/renewal_alert.py
> +        )
Boa! Feito 0ea4b9c :sparkles:

2022-02-03 21:22 UTC, rougeth commented on app/payment/management/commands/renewal_alert.py
> +        translation.deactivate()
Não tenho certeza, mas ainda que seja, acho que não vale a pena manter tudo isso pra ter texto em inglês com tradução em português. Mas vamos deixar isso para um próximo PR.

2022-02-03 21:22 UTC, rougeth approved these changes

2022-02-03 21:25 UTC, rougeth commented
@cuducos última questão antes de mergear, ideias de como podemos testar em produção? Chegou a pensar de algo? Posso ir atrás dos próximos email que deveriam ser enviados e ficar de olho, mas daí como confirmar que o email foi enviado? Podemos logar algumas informações, né?

2022-03-07 23:26 UTC, cuducos commented
> ideias de como podemos testar em produção?

O que fiz foi manualmente criar os vencimentos e rodar usando a saída de email de console (padrão do Django)

> Podemos logar algumas informações, né?

Como não achei nada estruturado de log na aplicação, sugeri o simples `stdout` no a92a1fb — por enquanto, tu acha que dá conta?

2022-03-10 21:15 UTC, rougeth commented
Rodei o script abaixo para pegar as próximas datas das notificações que devemos mandar com a mudança no PR:
```python
from datetime import datetime, timedelta
from django.db.models import Max, Q, Subquery
from django.utils import timezone
from app.payment.models import Payment

now = timezone.now()
now_plus_60 = now + timedelta(60)

active_members = Subquery(
    Payment.objects.annotate(expires_on=Max("valid_until"))
    .filter(expires_on__date__gt=now_plus_60.date())
    .values("member_id")
)

payments = Payment.objects.exclude(member__in=active_members).filter(valid_until__gte=now)

for payment in payments:
    print(payment.member.user.get_full_name())
    for day in (60, 30, 15, 7, 1):
        print(f"Alerta {day} dias: {(payment.valid_until-timedelta(days=day)).date()}")
    print(f"Válido até {payment.valid_until}")
    print("-" * 20)

```

Resultado foi:

```
Associada 1
Alerta 60 dias: 2022-01-11
Alerta 30 dias: 2022-02-10
Alerta 15 dias: 2022-02-25
Alerta 7 dias: 2022-03-05
Alerta 1 dias: 2022-03-11
Válido até 2022-03-12 06:53:02.248106+00:00
--------------------
Associada 2
Alerta 60 dias: 2022-01-10
Alerta 30 dias: 2022-02-09
Alerta 15 dias: 2022-02-24
Alerta 7 dias: 2022-03-04
Alerta 1 dias: 2022-03-10
Válido até 2022-03-11 11:21:42.405109+00:00
--------------------
Associada 3
Alerta 60 dias: 2022-01-19
Alerta 30 dias: 2022-02-18
Alerta 15 dias: 2022-03-05
Alerta 7 dias: 2022-03-13
Alerta 1 dias: 2022-03-19
Válido até 2022-03-20 17:03:39.859433+00:00
--------------------
Associada 4
Alerta 60 dias: 2022-02-25
Alerta 30 dias: 2022-03-27
Alerta 15 dias: 2022-04-11
Alerta 7 dias: 2022-04-19
Alerta 1 dias: 2022-04-25
Válido até 2022-04-26 16:45:07.562637+00:00
```

Fazendo merge hoje, devemos enviar as notificações:

```
Associada 1
Alerta 1 dias: 2022-03-11
--------------------
Associada 3
Alerta 7 dias: 2022-03-13
Alerta 1 dias: 2022-03-19
--------------------
Associada 4
Alerta 30 dias: 2022-03-27
Alerta 15 dias: 2022-04-11
Alerta 7 dias: 2022-04-19
Alerta 1 dias: 2022-04-25
```

Marquei no calendário para procurar os logs de envio para esses casos e atualizarei aqui o que encontrar. Valeu pelo trabalho @cuducos!

2022-03-10 21:15 UTC, merged